### ISSUE TITLE
paged with options hash and async

### ISSUE THREAD

**Issue by Matthieu82** [lelandrichardson/knockout-paged#1]
If the .paged() function is called with an options hash that does NOT have the async: true flag, but the url parameter IS passed, the plugin does not set async to true. This does happen when you pass the parameters to .paged simply as: .paged(5, '/some/url'). Either the documentation needs to be updated to reflect this or the code has to set async to true if one of the async-only options is passed in the hash.

**Comment by lelandrichardson** [comment]
this has been fixed. thanks!
